import './plugins/UserCommands.js'
import './plugins/OperatorCommands.js'
import './plugins/AdminCommands.js'
import './plugins/MasteradminCommands.js'
import './plugins/OwnerCommands.js'
import './plugins/Dedimania.js'
import './plugins/DefaultMessages.js'
import './plugins/UI.js'
