export default {
    clock: "https://trakman.ptrk.eu/icons/Clock.png",
    close: "https://trakman.ptrk.eu/icons/Close.png",
    closeHover: "https://trakman.ptrk.eu/icons/CloseHover.png",
    code: "https://trakman.ptrk.eu/icons/Code.png",
    codeBranch: "https://trakman.ptrk.eu/icons/CodeBranch.png",
    download: "https://trakman.ptrk.eu/icons/Download.png",
    downloadHover: "https://trakman.ptrk.eu/icons/DownloadHover.png",
    pageDoubleLeft: "https://trakman.ptrk.eu/icons/PageDoubleLeft.png",
    pageDoubleLeftHover: "https://trakman.ptrk.eu/icons/PageDoubleLeftHover.png",
    pageDoubleRight: "https://trakman.ptrk.eu/icons/PageDoubleRight.png",
    pageDoubleRightHover: "https://trakman.ptrk.eu/icons/PageDoubleRightHover.png",
    pageFirst: "https://trakman.ptrk.eu/icons/PageFirst.png",
    pageFirstHover: "https://trakman.ptrk.eu/icons/PageFirstHover.png",
    pageLast: "https://trakman.ptrk.eu/icons/PageLast.png",
    pageLastHover: "https://trakman.ptrk.eu/icons/PageLastHover.png",
    pageLeft: "https://trakman.ptrk.eu/icons/PageLeft.png",
    pageLeftHover: "https://trakman.ptrk.eu/icons/PageLeftHover.png",
    pageRight: "https://trakman.ptrk.eu/icons/PageRight.png",
    pageRightHover: "https://trakman.ptrk.eu/icons/PageRightHover.png",
    people: "https://trakman.ptrk.eu/icons/People.png",
    peopleGaming: "https://trakman.ptrk.eu/icons/PeopleGaming.png",
    tag: "https://trakman.ptrk.eu/icons/Tag.png",
    tagGreen: "https://trakman.ptrk.eu/icons/TagGreen.png",
    tagPinkCyan: "https://trakman.ptrk.eu/icons/TagPinkCyan.png",
    tagRed: "https://trakman.ptrk.eu/icons/TagRed.png",
    tagYellow: "https://trakman.ptrk.eu/icons/TagYellow.png",
    numberedList: "https://trakman.ptrk.eu/icons/NumberedList.png",
    stats: "https://trakman.ptrk.eu/icons/Stats.png",
    clockList: "https://trakman.ptrk.eu/icons/ClockList.png",
    voteReplay: "https://trakman.ptrk.eu/icons/VoteReplay.png",
    voteSkip: "https://trakman.ptrk.eu/icons/VoteSkip.png",
    payReplay: "https://trakman.ptrk.eu/icons/PayReplay.png",
    paySkip: "https://trakman.ptrk.eu/icons/PaySkip.png",
    karmaStats: "https://trakman.ptrk.eu/icons/KarmaStats.png",
    karmaPulse: "https://trakman.ptrk.eu/icons/KarmaPulse.png",
    peopleKarma: "https://trakman.ptrk.eu/icons/PeopleKarma.png",
    karmaGlobal: "https://trakman.ptrk.eu/icons/KarmaGlobal.png",
    karmaLocal: "https://trakman.ptrk.eu/icons/KarmaLocal.png",
    banlist: "https://trakman.ptrk.eu/icons/BanList.png",
    blacklist: "https://trakman.ptrk.eu/icons/BlacklistList.png",
    mutelist: "https://trakman.ptrk.eu/icons/MuteList.png",
    guestlist: "https://trakman.ptrk.eu/icons/GuestlistList.png",
    infoCircle: "https://trakman.ptrk.eu/icons/InfoCircle.png",
    tools: "https://trakman.ptrk.eu/icons/Tools.png",
    ban: "https://trakman.ptrk.eu/icons/Ban.png",
    banHover: "https://trakman.ptrk.eu/icons/BanHover.png",
    addToBlacklist: "https://trakman.ptrk.eu/icons/Ban.png",
    addToBlacklistHover: "https://trakman.ptrk.eu/icons/BlacklistHover.png",
    unban: "https://trakman.ptrk.eu/icons/Unban.png",
    unbanHover: "https://trakman.ptrk.eu/icons/UnbanHover.png",
    unblacklist: "https://trakman.ptrk.eu/icons/Unban.png",
    unblacklistHover: "https://trakman.ptrk.eu/icons/UnblacklistHover.png",
    addGuest: "https://trakman.ptrk.eu/icons/AddGuest.png",
    addGuestHover: "https://trakman.ptrk.eu/icons/AddGuestHover.png",
    removeGuest: "https://trakman.ptrk.eu/icons/RemoveGuest.png",
    removeGuestHover: "https://trakman.ptrk.eu/icons/RemoveGuestHover.png",
    mute: "https://trakman.ptrk.eu/icons/Mute.png",
    muteHover: "https://trakman.ptrk.eu/icons/MuteHover.png",
    unmute: "https://trakman.ptrk.eu/icons/Unmute.png",
    unmuteHover: "https://trakman.ptrk.eu/icons/UnmuteHover.png",
    forceSpectator: "https://trakman.ptrk.eu/icons/ForceSpectator.png",
    forceGaming: "https://trakman.ptrk.eu/icons/ForceGaming.png",
    chartDedi: "https://trakman.ptrk.eu/icons/ChartDedi.png",
    chartLive: "https://trakman.ptrk.eu/icons/ChartLive.png",
    chartLocal: "https://trakman.ptrk.eu/icons/ChartLocal.png",
    bestFinishes: "https://trakman.ptrk.eu/icons/BestFinishes.png",
    bestClock: "https://trakman.ptrk.eu/icons/BestClock.png",
    ongoingMap: "https://trakman.ptrk.eu/icons/OngoingMap.png",
    personBuilder: "https://trakman.ptrk.eu/icons/PersonBuilder.png",
    person: "https://trakman.ptrk.eu/icons/Person.png",
    personWorse: "https://trakman.ptrk.eu/icons/PersonWorse.png",
    personBetter: "https://trakman.ptrk.eu/icons/PersonBetter.png",
    clockAuthor: "https://trakman.ptrk.eu/icons/ClockAuthor.png",
    maniaExchange: "https://trakman.ptrk.eu/icons/ManiaExchange.png",
    cash: "https://trakman.ptrk.eu/icons/Cash.png",
    info: "https://trakman.ptrk.eu/icons/Info.png",
    gears: "https://trakman.ptrk.eu/icons/Gears.png",
    playerList: "https://trakman.ptrk.eu/icons/PlayerList.png",
    mapList: "https://trakman.ptrk.eu/icons/MapList.png",
    infoList: "https://trakman.ptrk.eu/icons/InfoList.png",
    placeholder: "https://trakman.ptrk.eu/icons/Placeholder.png",
    checkmark: "https://trakman.ptrk.eu/icons/Checkmark.png",
    cross: "https://trakman.ptrk.eu/icons/Cross.png",
    addMap: "https://trakman.ptrk.eu/icons/AddMap.png",
    removeMap: "https://trakman.ptrk.eu/icons/RemoveMap.png",
    thumbsUpF5: "https://trakman.ptrk.eu/icons/ThumbsUpF5.png",
    thumbsDownF6: "https://trakman.ptrk.eu/icons/ThumbsDownF6.png",
    F5: "https://trakman.ptrk.eu/icons/F5.png",
    F6: "https://trakman.ptrk.eu/icons/F6.png",
    blank: "http://maniacdn.net/undef.de/uaseco/blank.png",
    trackmania: "https://trakman.ptrk.eu/icons/Trackmania.png",
    calendarPlus: "https://trakman.ptrk.eu/icons/CalendarPlus.png",
    carExplode: "https://trakman.ptrk.eu/icons/CarExplode.png",
    moodNight: "https://trakman.ptrk.eu/icons/MoodNight.png",
    moodSunrise: "https://trakman.ptrk.eu/icons/MoodSunrise.png",
    moodSunset: "https://trakman.ptrk.eu/icons/MoodSunset.png",
    moodDay: "https://trakman.ptrk.eu/icons/MoodDay.png",
    mapStyle: "https://trakman.ptrk.eu/icons/MapStyle.png",
    mapRoutes: "https://trakman.ptrk.eu/icons/MapRoutes.png",
    difficultyEasy: "https://trakman.ptrk.eu/icons/DifficultyOne.png",
    difficultyMedium: "https://trakman.ptrk.eu/icons/DifficultyTwo.png",
    difficultyHard: "https://trakman.ptrk.eu/icons/DifficultyThree.png",
    difficultyExtreme: "https://trakman.ptrk.eu/icons/DifficultyFour.png",
    puzzle: "https://trakman.ptrk.eu/icons/Puzzle.png",
    leaderboardRating: "https://trakman.ptrk.eu/icons/LeaderboardRating.png",
    leaderboardRatingClassic: "https://trakman.ptrk.eu/icons/LeaderboardRatingClassic.png",
    leaderboardRatingNadeo: "https://trakman.ptrk.eu/icons/LeaderboardRatingNadeo.png",
    trophy: "https://trakman.ptrk.eu/icons/Trophy.png",
    trophyClassic: "https://trakman.ptrk.eu/icons/TrophyClassic.png",
    trophyNadeo: "https://trakman.ptrk.eu/icons/TrophyNadeo.png",
    kick: "https://trakman.ptrk.eu/icons/Kick.png",
    kickHover: "https://trakman.ptrk.eu/icons/KickHover.png",
    forceSpectatorHover: "https://trakman.ptrk.eu/icons/ForceSpectatorHover.png",
    forceGamingHover: "https://trakman.ptrk.eu/icons/ForceGamingHover.png",
    playerListHover: "https://trakman.ptrk.eu/icons/PlayerListHover.png",
    restartHover: "https://trakman.ptrk.eu/icons/RestartHover.png",
    restart: "https://trakman.ptrk.eu/icons/Restart.png",
    requeueHover: "https://trakman.ptrk.eu/icons/RequeueHover.png",
    requeue: "https://trakman.ptrk.eu/icons/Requeue.png",
    mapListHover: "https://trakman.ptrk.eu/icons/MapListHover.png",
    tagKacky: "https://trakman.ptrk.eu/icons/TagKacky.png",
    noScreenshot: "https://trakman.ptrk.eu/icons/NoScreenshot.png",
    waypoint: "https://trakman.ptrk.eu/icons/Waypoint.png",
    bgGreyOpaque50: "https://trakman.ptrk.eu/icons/GreyOpaque50.png",
    shuffleHover: "https://trakman.ptrk.eu/icons/ShuffleHover.png",
    shuffle: "https://trakman.ptrk.eu/icons/Shuffle.png",
    tagArcade: "https://trakman.ptrk.eu/icons/TagArcade.png",
    pause: "https://trakman.ptrk.eu/icons/Pause.png",
    pauseGreen: "https://trakman.ptrk.eu/icons/PauseHover.png",
    minus: "https://trakman.ptrk.eu/icons/Minus.png",
    minusGreen: "https://trakman.ptrk.eu/icons/MinusHover.png",
    plus: "https://trakman.ptrk.eu/icons/Plus.png",
    plusGreen: "https://trakman.ptrk.eu/icons/PlusHover.png",
    play: "https://trakman.ptrk.eu/icons/Play.png",
    playGreen: "https://trakman.ptrk.eu/icons/PlayHover.png",
    clockLap: "https://trakman.ptrk.eu/icons/ClockLap.png",
    lap: "https://trakman.ptrk.eu/icons/Laps.png",
    trakman: "https://trakman.ptrk.eu/icons/Trakman.png",
    flagFinish: "https://trakman.ptrk.eu/icons/FlagFinish.png",
    trophySilver: "https://trakman.ptrk.eu/icons/TrophySilver.png",
    trophyBronze: "https://trakman.ptrk.eu/icons/TrophyBronze.png",
    clockFire: "https://trakman.ptrk.eu/icons/ClockFire.png",
    lapsMode: "https://trakman.ptrk.eu/icons/LapsMode.png",
    teamsMode: "https://trakman.ptrk.eu/icons/TeamsMode.png",
    roundsMode: "https://trakman.ptrk.eu/icons/RoundsMode.png",
    stuntsMode: "https://trakman.ptrk.eu/icons/StuntsMode.png",
    servers: "https://trakman.ptrk.eu/icons/Servers.png",
    musicRemove: "https://trakman.ptrk.eu/icons/MusicRemove.png",
    musicRemoveHover: "https://trakman.ptrk.eu/icons/MusicRemoveHover.png",
    musicAdd: "https://trakman.ptrk.eu/icons/MusicAdd.png",
    musicAddHover: "https://trakman.ptrk.eu/icons/MusicAddHover.png",
    musicList: "https://trakman.ptrk.eu/icons/MusicList.png",
    disk: "https://trakman.ptrk.eu/icons/Disk.png",
    music: "https://trakman.ptrk.eu/icons/Music.png",
    exclamation: "https://trakman.ptrk.eu/icons/Exclamation.png",
    warn: "https://trakman.ptrk.eu/icons/Warn.png",
    personMusic: "https://trakman.ptrk.eu/icons/PersonMusic.png",
    promotePlayer: "https://trakman.ptrk.eu/icons/PromotePlayer.png",
    promotePlayerHover: "https://trakman.ptrk.eu/icons/PromotePlayerHover.png",
    demotePlayer: "https://trakman.ptrk.eu/icons/DemotePlayer.png",
    demotePlayerHover: "https://trakman.ptrk.eu/icons/DemotePlayerHover.png",
    trashcanDelete: "https://trakman.ptrk.eu/icons/TrashDelete.png",
    trashcanDeleteHover: "https://trakman.ptrk.eu/icons/TrashDeleteHover.png",

    get preloadedIcons() {
        return [
            this.close,
            this.closeHover,
            this.pageDoubleLeft,
            this.pageDoubleLeftHover,
            this.pageDoubleRight,
            this.pageDoubleRightHover,
            this.pageFirst,
            this.pageFirstHover,
            this.pageLast,
            this.pageLastHover,
            this.pageLeft,
            this.pageLeftHover,
            this.pageRight,
            this.pageRightHover
        ]
    }
}
