interface EndMapInfo {
    readonly id: string
    readonly name: string
    readonly fileName: string
    readonly author: string
    readonly environment: string
    readonly mood: string
    readonly bronzeTime: number
    readonly silverTime: number
    readonly goldTime: number
    readonly authorTime: number
    readonly copperPrice: number
    readonly lapRace: boolean
    readonly lapsAmount: number
    readonly checkpointsAmount: number
    readonly records: TMRecord[]
    readonly isRestarted: boolean
    readonly wasWarmUp: boolean
    readonly continuesOnNextMap: boolean
}
