interface RecordInfo {
  readonly map: string
  readonly login: string
  readonly time: number
  readonly date: Date
  readonly checkpoints: number[]
  readonly nickname: string
  readonly nation: string
  readonly nationCode: string
  readonly timePlayed: number
  readonly joinTimestamp: number
  readonly wins: number
  readonly privilege: number
  readonly visits: number
  readonly position: number
  readonly previousPosition: number
  readonly previousTime: number
  readonly playerId: number
  readonly ip: string
  readonly region: string
  readonly isUnited: boolean
}
